import type { Chapter } from '@venomous-snake/shared-types';

export const chapters: Chapter[] = [
  {
    id: 1,
    titleKey: 'chapters.ch01.title',
    descriptionKey: 'chapters.ch01.description',
    floor: 'lobby',
    challenges: [
      'ch01_01_hello_world',
      'ch01_02_variables',
      'ch01_03_math_ops',
      'ch01_04_string_types',
      'ch01_05_float_calculations',
      'ch01_06_string_concatenation',
      'ch01_07_multiple_prints',
      'ch01_08_comments',
    ],
    conceptsCovered: [
      'print',
      'strings',
      'variables',
      'int',
      'float',
      'arithmetic',
      'type',
      'string_concatenation',
      'comments',
      'escape_characters',
    ],
  },
  {
    id: 2,
    titleKey: 'chapters.ch02.title',
    descriptionKey: 'chapters.ch02.description',
    floor: 'floor_2',
    challenges: [
      'ch02_01_string_methods',
      'ch02_02_string_indexing',
      'ch02_03_string_slicing',
      'ch02_04_fstrings_basics',
      'ch02_05_input_basics',
      'ch02_06_type_conversion',
      'ch02_07_string_formatting',
      'ch02_08_len_and_string_ops',
    ],
    conceptsCovered: [
      'string_methods',
      'string_indexing',
      'string_slicing',
      'fstrings',
      'input',
      'type_conversion',
      'len',
    ],
  },
  {
    id: 3,
    titleKey: 'chapters.ch03.title',
    descriptionKey: 'chapters.ch03.description',
    floor: 'floor_3',
    challenges: [
      'ch03_01_simple_if',
      'ch03_02_if_else',
      'ch03_03_comparison_operators',
      'ch03_04_if_elif_else',
      'ch03_05_logical_operators',
      'ch03_06_nested_if',
      'ch03_07_boolean_variables',
      'ch03_08_complex_conditions',
    ],
    conceptsCovered: [
      'if_statement',
      'if_else',
      'elif',
      'comparison_operators',
      'logical_operators',
      'nested_if',
      'boolean',
    ],
  },
  {
    id: 4,
    titleKey: 'chapters.ch04.title',
    descriptionKey: 'chapters.ch04.description',
    floor: 'floor_4',
    challenges: [
      'ch04_01_simple_for_loop',
      'ch04_02_range_basics',
      'ch04_03_for_with_range',
      'ch04_04_while_basics',
      'ch04_05_while_condition',
      'ch04_06_break_statement',
      'ch04_07_continue_statement',
      'ch04_08_nested_loops',
      'ch04_09_loop_accumulator',
      'ch04_10_for_enumerate',
    ],
    conceptsCovered: [
      'for_loop',
      'while_loop',
      'range',
      'break',
      'continue',
      'nested_loops',
      'enumerate',
      'accumulator',
    ],
  },
  {
    id: 5,
    titleKey: 'chapters.ch05.title',
    descriptionKey: 'chapters.ch05.description',
    floor: 'floor_5',
    challenges: [
      'ch05_01_simple_function',
      'ch05_02_function_return',
      'ch05_03_multiple_parameters',
      'ch05_04_default_parameters',
      'ch05_05_return_multiple',
      'ch05_06_functions_calling_functions',
      'ch05_07_scope',
      'ch05_08_args',
      'ch05_09_kwargs',
      'ch05_10_lambda',
    ],
    conceptsCovered: [
      'function_definition',
      'parameters',
      'return_statement',
      'default_parameters',
      'scope',
      'args',
      'kwargs',
      'lambda',
    ],
  },
  {
    id: 6,
    titleKey: 'chapters.ch06.title',
    descriptionKey: 'chapters.ch06.description',
    floor: 'floor_6',
    challenges: [
      'ch06_01_create_list',
      'ch06_02_list_methods',
      'ch06_03_list_slicing',
      'ch06_04_list_comprehension',
      'ch06_05_tuples',
      'ch06_06_dictionaries',
      'ch06_07_dict_methods',
      'ch06_08_nested_dicts',
      'ch06_09_sets',
      'ch06_10_combining_collections',
    ],
    conceptsCovered: [
      'lists',
      'list_methods',
      'list_comprehension',
      'tuples',
      'dictionaries',
      'dict_methods',
      'sets',
      'collections',
    ],
  },
  {
    id: 7,
    titleKey: 'chapters.ch07.title',
    descriptionKey: 'chapters.ch07.description',
    floor: 'floor_7',
    challenges: [
      'ch07_01_read_file',
      'ch07_02_write_file',
      'ch07_03_file_line_processing',
      'ch07_04_csv_parsing',
      'ch07_05_string_split_join',
      'ch07_06_with_statement',
      'ch07_07_json_parsing',
      'ch07_08_data_transformation',
    ],
    conceptsCovered: [
      'io_stringio',
      'file_read',
      'file_write',
      'line_processing',
      'csv_parsing',
      'string_split_join',
      'with_statement',
      'json_parsing',
      'data_transformation',
    ],
  },
  {
    id: 8,
    titleKey: 'chapters.ch08.title',
    descriptionKey: 'chapters.ch08.description',
    floor: 'floor_8',
    challenges: [
      'ch08_01_try_except',
      'ch08_02_multiple_except',
      'ch08_03_try_except_else_finally',
      'ch08_04_raising_exceptions',
      'ch08_05_custom_exception_classes',
      'ch08_06_input_validation_with_errors',
      'ch08_07_graceful_degradation',
      'ch08_08_error_handling_in_loops',
    ],
    conceptsCovered: [
      'try_except',
      'multiple_except',
      'else_finally',
      'raise_exception',
      'custom_exceptions',
      'input_validation',
      'graceful_degradation',
      'error_recovery',
    ],
  },
  {
    id: 9,
    titleKey: 'chapters.ch09.title',
    descriptionKey: 'chapters.ch09.description',
    floor: 'floor_9',
    challenges: [
      'ch09_01_importing_modules',
      'ch09_02_from_import',
      'ch09_03_lambda_functions',
      'ch09_04_map_function',
      'ch09_05_filter_function',
      'ch09_06_list_comprehension_conditionals',
      'ch09_07_dictionary_comprehension',
      'ch09_08_string_formatting_advanced',
      'ch09_09_regular_expressions',
      'ch09_10_combining_tools',
    ],
    conceptsCovered: [
      'import_module',
      'from_import',
      'lambda',
      'map',
      'filter',
      'conditional_comprehension',
      'dict_comprehension',
      'string_formatting',
      'regular_expressions',
      'functional_chaining',
    ],
  },
  {
    id: 10,
    titleKey: 'chapters.ch10.title',
    descriptionKey: 'chapters.ch10.description',
    floor: 'floor_10',
    challenges: [
      'ch10_01_simple_class',
      'ch10_02_methods',
      'ch10_03_init_constructor',
      'ch10_04_str_repr',
      'ch10_05_inheritance',
      'ch10_06_method_override',
      'ch10_07_encapsulation',
      'ch10_08_class_static_methods',
      'ch10_09_composition',
      'ch10_10_polymorphism',
    ],
    conceptsCovered: [
      'classes',
      'methods',
      'constructor',
      'str_repr',
      'inheritance',
      'method_override',
      'encapsulation',
      'classmethod',
      'staticmethod',
      'composition',
      'polymorphism',
    ],
  },
  {
    id: 11,
    titleKey: 'chapters.ch11.title',
    descriptionKey: 'chapters.ch11.description',
    floor: 'floor_11',
    challenges: [
      'ch11_01_type_hints',
      'ch11_02_dataclasses',
      'ch11_03_assert_statements',
      'ch11_04_writing_simple_tests',
      'ch11_05_docstrings',
      'ch11_06_constants_enums',
      'ch11_07_list_typing',
      'ch11_08_putting_it_together',
    ],
    conceptsCovered: [
      'type_hints',
      'dataclasses',
      'assert',
      'testing',
      'docstrings',
      'enums',
      'typing_module',
      'professional_python',
    ],
  },
  {
    id: 12,
    titleKey: 'chapters.ch12.title',
    descriptionKey: 'chapters.ch12.description',
    floor: 'floor_12',
    challenges: [
      'ch12_01_generators',
      'ch12_02_generator_expressions',
      'ch12_03_decorators_basics',
      'ch12_04_decorators_with_args',
      'ch12_05_context_managers',
      'ch12_06_async_basics',
      'ch12_07_pattern_matching',
      'ch12_08_walrus_operator',
      'ch12_09_advanced_comprehensions',
      'ch12_10_final_showdown',
    ],
    bossChallenge: 'ch12_10_final_showdown',
    conceptsCovered: [
      'generators',
      'generator_expressions',
      'decorators',
      'context_managers',
      'async_await',
      'pattern_matching',
      'walrus_operator',
      'advanced_comprehensions',
    ],
  },
];
