import type { Chapter } from '@venomous-snake/shared-types';

export const chapters: Chapter[] = [
  {
    id: 1,
    titleKey: 'chapters.ch01.title',
    descriptionKey: 'chapters.ch01.description',
    floor: 'lobby',
    challenges: [
      'ch01_01_hello_world',
      'ch01_02_variables',
      'ch01_03_math_ops',
      'ch01_04_string_types',
      'ch01_05_float_calculations',
      'ch01_06_string_concatenation',
      'ch01_07_multiple_prints',
      'ch01_08_comments',
    ],
    conceptsCovered: [
      'print',
      'strings',
      'variables',
      'int',
      'float',
      'arithmetic',
      'type',
      'string_concatenation',
      'comments',
      'escape_characters',
    ],
  },
  {
    id: 2,
    titleKey: 'chapters.ch02.title',
    descriptionKey: 'chapters.ch02.description',
    floor: 'floor_2',
    challenges: [
      'ch02_01_string_methods',
      'ch02_02_string_indexing',
      'ch02_03_string_slicing',
      'ch02_04_fstrings_basics',
      'ch02_05_input_basics',
      'ch02_06_type_conversion',
      'ch02_07_string_formatting',
      'ch02_08_len_and_string_ops',
    ],
    conceptsCovered: [
      'string_methods',
      'string_indexing',
      'string_slicing',
      'fstrings',
      'input',
      'type_conversion',
      'len',
    ],
  },
  {
    id: 3,
    titleKey: 'chapters.ch03.title',
    descriptionKey: 'chapters.ch03.description',
    floor: 'floor_3',
    challenges: [
      'ch03_01_simple_if',
      'ch03_02_if_else',
      'ch03_03_comparison_operators',
      'ch03_04_if_elif_else',
      'ch03_05_logical_operators',
      'ch03_06_nested_if',
      'ch03_07_boolean_variables',
      'ch03_08_complex_conditions',
    ],
    conceptsCovered: [
      'if_statement',
      'if_else',
      'elif',
      'comparison_operators',
      'logical_operators',
      'nested_if',
      'boolean',
    ],
  },
  {
    id: 4,
    titleKey: 'chapters.ch04.title',
    descriptionKey: 'chapters.ch04.description',
    floor: 'floor_4',
    challenges: [
      'ch04_01_simple_for_loop',
      'ch04_02_range_basics',
      'ch04_03_for_with_range',
      'ch04_04_while_basics',
      'ch04_05_while_condition',
      'ch04_06_break_statement',
      'ch04_07_continue_statement',
      'ch04_08_nested_loops',
      'ch04_09_loop_accumulator',
      'ch04_10_for_enumerate',
    ],
    conceptsCovered: [
      'for_loop',
      'while_loop',
      'range',
      'break',
      'continue',
      'nested_loops',
      'enumerate',
      'accumulator',
    ],
  },
  {
    id: 5,
    titleKey: 'chapters.ch05.title',
    descriptionKey: 'chapters.ch05.description',
    floor: 'floor_5',
    challenges: [
      'ch05_01_simple_function',
      'ch05_02_function_return',
      'ch05_03_multiple_parameters',
      'ch05_04_default_parameters',
      'ch05_05_return_multiple',
      'ch05_06_functions_calling_functions',
      'ch05_07_scope',
      'ch05_08_args',
      'ch05_09_kwargs',
      'ch05_10_lambda',
    ],
    conceptsCovered: [
      'function_definition',
      'parameters',
      'return_statement',
      'default_parameters',
      'scope',
      'args',
      'kwargs',
      'lambda',
    ],
  },
  {
    id: 6,
    titleKey: 'chapters.ch06.title',
    descriptionKey: 'chapters.ch06.description',
    floor: 'floor_6',
    challenges: [
      'ch06_01_create_list',
      'ch06_02_list_methods',
      'ch06_03_list_slicing',
      'ch06_04_list_comprehension',
      'ch06_05_tuples',
      'ch06_06_dictionaries',
      'ch06_07_dict_methods',
      'ch06_08_nested_dicts',
      'ch06_09_sets',
      'ch06_10_combining_collections',
    ],
    conceptsCovered: [
      'lists',
      'list_methods',
      'list_comprehension',
      'tuples',
      'dictionaries',
      'dict_methods',
      'sets',
      'collections',
    ],
  },
];
